import { SelectOption } from "@/src/shared";

export type PresetTimezone = {
  id: string;
  label: string;
  name: string;
  abbr: string;
  hours: number;
  minutes: number;
};

export const defaultImages = {
  profile:
    "https://firebasestorage.googleapis.com/v0/b/turndown-6c530.firebasestorage.app/o/defaults%2Fdefault_profile.jpg?alt=media&token=c34d7d86-4c5c-4de8-bd59-d62c5c5b1e85",
  home: "https://firebasestorage.googleapis.com/v0/b/turndown-6c530.firebasestorage.app/o/defaults%2Fhome-image.jpg?alt=media&token=cc84f968-a0ec-4e5b-8618-022d90274cb5",
};

export const statesAndTerritories: SelectOption[] = [
  { label: "Alabama", value: "Alabama" },
  { label: "Alaska", value: "Alaska" },
  { label: "American Samoa", value: "American Samoa" },
  { label: "Arizona", value: "Arizona" },
  { label: "Arkansas", value: "Arkansas" },
  { label: "California", value: "California" },
  { label: "Colorado", value: "Colorado" },
  { label: "Connecticut", value: "Connecticut" },
  { label: "Delaware", value: "Delaware" },
  { label: "District of Columbia", value: "District of Columbia" },
  { label: "Florida", value: "Florida" },
  { label: "Georgia", value: "Georgia" },
  { label: "Guam", value: "Guam" },
  { label: "Hawaii", value: "Hawaii" },
  { label: "Idaho", value: "Idaho" },
  { label: "Illinois", value: "Illinois" },
  { label: "Indiana", value: "Indiana" },
  { label: "Iowa", value: "Iowa" },
  { label: "Kansas", value: "Kansas" },
  { label: "Kentucky", value: "Kentucky" },
  { label: "Louisiana", value: "Louisiana" },
  { label: "Maine", value: "Maine" },
  { label: "Maryland", value: "Maryland" },
  { label: "Massachusetts", value: "Massachusetts" },
  { label: "Michigan", value: "Michigan" },
  { label: "Minnesota", value: "Minnesota" },
  { label: "Mississippi", value: "Mississippi" },
  { label: "Missouri", value: "Missouri" },
  { label: "Montana", value: "Montana" },
  { label: "Nebraska", value: "Nebraska" },
  { label: "Nevada", value: "Nevada" },
  { label: "New Hampshire", value: "New Hampshire" },
  { label: "New Jersey", value: "New Jersey" },
  { label: "New Mexico", value: "New Mexico" },
  { label: "New York", value: "New York" },
  { label: "North Carolina", value: "North Carolina" },
  { label: "North Dakota", value: "North Dakota" },
  { label: "Northern Mariana Islands", value: "Northern Mariana Islands" },
  { label: "Ohio", value: "Ohio" },
  { label: "Oklahoma", value: "Oklahoma" },
  { label: "Oregon", value: "Oregon" },
  { label: "Pennsylvania", value: "Pennsylvania" },
  { label: "Puerto Rico", value: "Puerto Rico" },
  { label: "Rhode Island", value: "Rhode Island" },
  { label: "South Carolina", value: "South Carolina" },
  { label: "South Dakota", value: "South Dakota" },
  { label: "Tennessee", value: "Tennessee" },
  { label: "Texas", value: "Texas" },
  {
    label: "United States Virgin Islands",
    value: "United States Virgin Islands",
  },
  { label: "Utah", value: "Utah" },
  { label: "Vermont", value: "Vermont" },
  { label: "Virginia", value: "Virginia" },
  { label: "Washington", value: "Washington" },
  { label: "West Virginia", value: "West Virginia" },
  { label: "Wisconsin", value: "Wisconsin" },
  { label: "Wyoming", value: "Wyoming" },
];

export const ALL_TIMEZONES: PresetTimezone[] = [
  {
    id: "Etc/UTC",
    label: "Etc/UTC",
    name: "Etc/UTC",
    abbr: "UTC",
    hours: 0,
    minutes: 0,
  },
  {
    id: "Africa/Abidjan",
    label: "Africa/Abidjan",
    name: "Africa/Abidjan",
    abbr: "GMT",
    hours: 0,
    minutes: 0,
  },
  {
    id: "Africa/Accra",
    label: "Africa/Accra",
    name: "Africa/Accra",
    abbr: "GMT",
    hours: 0,
    minutes: 0,
  },
  {
    id: "Africa/Cairo",
    label: "Africa/Cairo",
    name: "Africa/Cairo",
    abbr: "EET",
    hours: 3,
    minutes: 0,
  },
  {
    id: "Africa/Johannesburg",
    label: "Africa/Johannesburg",
    name: "Africa/Johannesburg",
    abbr: "SAST",
    hours: 2,
    minutes: 0,
  },
  {
    id: "Africa/Lagos",
    label: "Africa/Lagos",
    name: "Africa/Lagos",
    abbr: "WAT",
    hours: 1,
    minutes: 0,
  },
  {
    id: "America/Anchorage",
    label: "America/Anchorage",
    name: "America/Anchorage",
    abbr: "AKST",
    hours: -8,
    minutes: 0,
  },
  {
    id: "America/Argentina/Buenos_Aires",
    label: "America/Argentina/Buenos_Aires",
    name: "America/Argentina/Buenos_Aires",
    abbr: "ART",
    hours: -3,
    minutes: 0,
  },
  {
    id: "America/Bogota",
    label: "America/Bogota",
    name: "America/Bogota",
    abbr: "COT",
    hours: -5,
    minutes: 0,
  },
  {
    id: "America/Caracas",
    label: "America/Caracas",
    name: "America/Caracas",
    abbr: "VET",
    hours: -4,
    minutes: 0,
  },
  {
    id: "America/Chicago",
    label: "America/Chicago",
    name: "America/Chicago",
    abbr: "CST",
    hours: -5,
    minutes: 0,
  },
  {
    id: "America/Denver",
    label: "America/Denver",
    name: "America/Denver",
    abbr: "MST",
    hours: -6,
    minutes: 0,
  },
  {
    id: "America/Guatemala",
    label: "America/Guatemala",
    name: "America/Guatemala",
    abbr: "CST",
    hours: -6,
    minutes: 0,
  },
  {
    id: "America/Halifax",
    label: "America/Halifax",
    name: "America/Halifax",
    abbr: "AST",
    hours: -3,
    minutes: 0,
  },
  {
    id: "America/La_Paz",
    label: "America/La_Paz",
    name: "America/La_Paz",
    abbr: "BOT",
    hours: -4,
    minutes: 0,
  },
  {
    id: "America/Los_Angeles",
    label: "America/Los_Angeles",
    name: "America/Los_Angeles",
    abbr: "PST",
    hours: -7,
    minutes: 0,
  },
  {
    id: "America/Mexico_City",
    label: "America/Mexico_City",
    name: "America/Mexico_City",
    abbr: "CST",
    hours: -6,
    minutes: 0,
  },
  {
    id: "America/New_York",
    label: "America/New_York",
    name: "America/New_York",
    abbr: "EST",
    hours: -4,
    minutes: 0,
  },
  {
    id: "America/Phoenix",
    label: "America/Phoenix",
    name: "America/Phoenix",
    abbr: "MST",
    hours: -7,
    minutes: 0,
  },
  {
    id: "America/Santiago",
    label: "America/Santiago",
    name: "America/Santiago",
    abbr: "CLT",
    hours: -3,
    minutes: 0,
  },
  {
    id: "America/Sao_Paulo",
    label: "America/Sao_Paulo",
    name: "America/Sao_Paulo",
    abbr: "BRT",
    hours: -3,
    minutes: 0,
  },
  {
    id: "America/Toronto",
    label: "America/Toronto",
    name: "America/Toronto",
    abbr: "EST",
    hours: -4,
    minutes: 0,
  },
  {
    id: "Antarctica/Casey",
    label: "Antarctica/Casey",
    name: "Antarctica/Casey",
    abbr: "AWST",
    hours: 8,
    minutes: 0,
  },
  {
    id: "Asia/Baghdad",
    label: "Asia/Baghdad",
    name: "Asia/Baghdad",
    abbr: "AST",
    hours: 3,
    minutes: 0,
  },
  {
    id: "Asia/Bangkok",
    label: "Asia/Bangkok",
    name: "Asia/Bangkok",
    abbr: "ICT",
    hours: 7,
    minutes: 0,
  },
  {
    id: "Asia/Beirut",
    label: "Asia/Beirut",
    name: "Asia/Beirut",
    abbr: "EET",
    hours: 3,
    minutes: 0,
  },
  {
    id: "Asia/Dubai",
    label: "Asia/Dubai",
    name: "Asia/Dubai",
    abbr: "GST",
    hours: 4,
    minutes: 0,
  },
  {
    id: "Asia/Hong_Kong",
    label: "Asia/Hong_Kong",
    name: "Asia/Hong_Kong",
    abbr: "HKT",
    hours: 8,
    minutes: 0,
  },
  {
    id: "Asia/Jakarta",
    label: "Asia/Jakarta",
    name: "Asia/Jakarta",
    abbr: "WIB",
    hours: 7,
    minutes: 0,
  },
  {
    id: "Asia/Karachi",
    label: "Asia/Karachi",
    name: "Asia/Karachi",
    abbr: "PKT",
    hours: 5,
    minutes: 0,
  },
  {
    id: "Asia/Kathmandu",
    label: "Asia/Kathmandu",
    name: "Asia/Kathmandu",
    abbr: "NPT",
    hours: 5,
    minutes: 45,
  },
  {
    id: "Asia/Kolkata",
    label: "Asia/Kolkata",
    name: "Asia/Kolkata",
    abbr: "IST",
    hours: 5,
    minutes: 30,
  },
  {
    id: "Asia/Kuala_Lumpur",
    label: "Asia/Kuala_Lumpur",
    name: "Asia/Kuala_Lumpur",
    abbr: "MYT",
    hours: 8,
    minutes: 0,
  },
  {
    id: "Asia/Muscat",
    label: "Asia/Muscat",
    name: "Asia/Muscat",
    abbr: "GST",
    hours: 4,
    minutes: 0,
  },
  {
    id: "Asia/Riyadh",
    label: "Asia/Riyadh",
    name: "Asia/Riyadh",
    abbr: "AST",
    hours: 3,
    minutes: 0,
  },
  {
    id: "Asia/Seoul",
    label: "Asia/Seoul",
    name: "Asia/Seoul",
    abbr: "KST",
    hours: 9,
    minutes: 0,
  },
  {
    id: "Asia/Shanghai",
    label: "Asia/Shanghai",
    name: "Asia/Shanghai",
    abbr: "CST",
    hours: 8,
    minutes: 0,
  },
  {
    id: "Asia/Singapore",
    label: "Asia/Singapore",
    name: "Asia/Singapore",
    abbr: "SGT",
    hours: 8,
    minutes: 0,
  },
  {
    id: "Asia/Tokyo",
    label: "Asia/Tokyo",
    name: "Asia/Tokyo",
    abbr: "JST",
    hours: 9,
    minutes: 0,
  },
  {
    id: "Asia/Yerevan",
    label: "Asia/Yerevan",
    name: "Asia/Yerevan",
    abbr: "AMT",
    hours: 4,
    minutes: 0,
  },
  {
    id: "Atlantic/Azores",
    label: "Atlantic/Azores",
    name: "Atlantic/Azores",
    abbr: "AZOT",
    hours: 0,
    minutes: 0,
  },
  {
    id: "Atlantic/Reykjavik",
    label: "Atlantic/Reykjavik",
    name: "Atlantic/Reykjavik",
    abbr: "GMT",
    hours: 0,
    minutes: 0,
  },
  {
    id: "Australia/Adelaide",
    label: "Australia/Adelaide",
    name: "Australia/Adelaide",
    abbr: "ACST",
    hours: 9,
    minutes: 30,
  },
  {
    id: "Australia/Brisbane",
    label: "Australia/Brisbane",
    name: "Australia/Brisbane",
    abbr: "AEST",
    hours: 10,
    minutes: 0,
  },
  {
    id: "Australia/Perth",
    label: "Australia/Perth",
    name: "Australia/Perth",
    abbr: "AWST",
    hours: 8,
    minutes: 0,
  },
  {
    id: "Australia/Sydney",
    label: "Australia/Sydney",
    name: "Australia/Sydney",
    abbr: "AEST",
    hours: 10,
    minutes: 0,
  },
  {
    id: "Europe/Amsterdam",
    label: "Europe/Amsterdam",
    name: "Europe/Amsterdam",
    abbr: "CET",
    hours: 2,
    minutes: 0,
  },
  {
    id: "Europe/Athens",
    label: "Europe/Athens",
    name: "Europe/Athens",
    abbr: "EET",
    hours: 3,
    minutes: 0,
  },
  {
    id: "Europe/Berlin",
    label: "Europe/Berlin",
    name: "Europe/Berlin",
    abbr: "CET",
    hours: 2,
    minutes: 0,
  },
  {
    id: "Europe/Dublin",
    label: "Europe/Dublin",
    name: "Europe/Dublin",
    abbr: "GMT",
    hours: 1,
    minutes: 0,
  },
  {
    id: "Europe/Istanbul",
    label: "Europe/Istanbul",
    name: "Europe/Istanbul",
    abbr: "TRT",
    hours: 3,
    minutes: 0,
  },
  {
    id: "Europe/Lisbon",
    label: "Europe/Lisbon",
    name: "Europe/Lisbon",
    abbr: "WET",
    hours: 1,
    minutes: 0,
  },
  {
    id: "Europe/London",
    label: "Europe/London",
    name: "Europe/London",
    abbr: "GMT",
    hours: 1,
    minutes: 0,
  },
  {
    id: "Europe/Madrid",
    label: "Europe/Madrid",
    name: "Europe/Madrid",
    abbr: "CET",
    hours: 2,
    minutes: 0,
  },
  {
    id: "Europe/Moscow",
    label: "Europe/Moscow",
    name: "Europe/Moscow",
    abbr: "MSK",
    hours: 3,
    minutes: 0,
  },
  {
    id: "Europe/Paris",
    label: "Europe/Paris",
    name: "Europe/Paris",
    abbr: "CET",
    hours: 2,
    minutes: 0,
  },
  {
    id: "Europe/Zurich",
    label: "Europe/Zurich",
    name: "Europe/Zurich",
    abbr: "CET",
    hours: 2,
    minutes: 0,
  },
  {
    id: "Indian/Maldives",
    label: "Indian/Maldives",
    name: "Indian/Maldives",
    abbr: "MVT",
    hours: 5,
    minutes: 0,
  },
  {
    id: "Indian/Mauritius",
    label: "Indian/Mauritius",
    name: "Indian/Mauritius",
    abbr: "MUT",
    hours: 4,
    minutes: 0,
  },
  {
    id: "Pacific/Auckland",
    label: "Pacific/Auckland",
    name: "Pacific/Auckland",
    abbr: "NZST",
    hours: 12,
    minutes: 0,
  },
  {
    id: "Pacific/Honolulu",
    label: "Pacific/Honolulu",
    name: "Pacific/Honolulu",
    abbr: "HST",
    hours: -10,
    minutes: 0,
  },
];
